export const BasketTranslationDE = {
  adjustAllOrderItemsHeader: 'Produkte in deiner Tasche haben sich verändert.',
  adjustAllOrderItemsText: 'Bitte überprüfe deine Tasche bevor du zur Kasse gehst.',
  adjustOrderItemHeader: 'Produktmenge angepasst',
  article: ' Artikel',
  checkOut: 'Zur Kasse',
  clearBasket: 'Leeren',
  deliveryCharges: 'zzgl. $Price Liefergebühren',
  deposit: '+ $Price Pfand',
  discoverProducts: 'Produkte entdecken',
  emptyCartHeader: 'Warenkorb leeren',
  emptyCartText: 'Willst du alle Produkte aus dem Warenkorb entfernen?',
  emptyShoppingCart: 'Noch nichts in der Tasche',
  keepProducts: 'Produkte behalten',
  minimumOrderValue: ' Der Mindestbestellwert liegt bei 15,00 €',
  missingAmountToFreeShipping: 'Nur noch $Price bis zum kostenlosen Versand!',
  missingAmountToMOV: 'Nur noch $Price bis zum Mindestbestellwert!',
  productNotAvilableHeader: 'Produkt nicht mehr verfügbar',
  productNotAvilableText: 'Das folgende Produkt ist ausverkauft und wurde aus deiner Tasche entfernt.',
  removeProducts: 'Produkte entfernen',
  searchForProducts: ' Suche nach Produkten oder stöbere in den Kategorien.',
  shoppingCart: 'Warenkorb',
  updateNow: 'Jetzt aktualisieren',
  upSelling: 'Bevor du’s vergisst...',
};
