// ***************************************************** //
//                  AUTO GENERATED FILE                  //
// This file was generated by this script: yarn run icon //
//          Do not change the content manually!          //
// ***************************************************** //

export enum KS_ICON {
  ADD = 'add',
  ARROW_DOWN_1 = 'arrow-down-1',
  ARROW_LEFT_2 = 'arrow-left-2',
  ARROW_RIGHT_3 = 'arrow-right-3',
  ARROW_UP_2 = 'arrow-up-2',
  BAG_2 = 'bag-2',
  BAG_CROSS = 'bag-cross',
  BAG_TICK = 'bag-tick',
  BAG_TIMER = 'bag-timer',
  CALENDAR = 'calendar',
  CALL = 'call',
  CARD = 'card',
  CHART_21 = 'chart-21',
  CLOCK = 'clock',
  CLOSE = 'close',
  CLOSE_CIRCLE = 'close-circle',
  EDIT = 'edit',
  EMPTY_WALLET = 'empty-wallet',
  EXPORT_3 = 'export-3',
  EYE = 'eye',
  EYE_SLASH = 'eye-slash',
  GPS = 'gps',
  GUEST_LOGIN = 'guest-login',
  HEART = 'heart',
  HOME_2 = 'home-2',
  INFO_CIRCLE = 'info-circle',
  INFORMATION_FILL = 'information-fill',
  LOCATION = 'location',
  LOCATION_CROSS = 'location-cross',
  LOCATION_TICK = 'location-tick',
  LOCK2 = 'lock2',
  MINUS = 'minus',
  MORE_VERTICAL = 'more-vertical',
  PROFILE = 'profile',
  SEARCH_NORMAL_1 = 'search-normal-1',
  SMS = 'sms',
  TICK = 'tick',
  TICKET_DISCOUNT = 'ticket-discount',
  TRASH = 'trash',
  TRUCK_FAST = 'truck-fast',
}

export enum KS_ICON_STYLE {
  BOLD = 'bold',
  OUTLINE = 'outline',
}
