// eslint-disable-next-line @typescript-eslint/typedef
export const authTranslationsDE = {
  alreadyHaveAnAccount: 'Du hast bereits einen Account?',
  backToLogin: 'Zum Anmelden',
  backToSelection: 'Zurück zur Auswahl',
  backToStart: 'Zurück zum Start',
  browseAsGuest: 'Als Gast stöbern',
  browseAsGuestButton: 'In Aschaffenburg stöbern',
  browseAsGuestHeading: `Bis hier liefern wir's`,
  deliveryAreaList: `Aschaffenburg | Großostheim | Alzenau | Kahlgrund | Bessenbach`,
  emailAddress: 'E-Mail-Adresse',
  emailAddressValidation: 'Bitte gib die E-Mail-Adresse im richtigen Format ein: deinname@beispiel.de',
  emailLogin: 'E-Mail Login',
  firstName: 'Vorname',
  firstNameValidation: 'Bitte gib deinen Vornamen ein',
  forgetPassword: 'Kennwort vergessen?',
  forgetPasswordHeading: 'Kennwort vergessen',
  lastName: 'Nachname',
  lastNameValidation: 'Bitte gib deinen Nachnamen ein',
  login: 'Anmelden',
  loginHeading: 'Jetzt anmelden & gleich liefern lassen',
  loginSccessful: 'Anmeldung erfolgreich',
  loginWelcome: 'Schön dich wiederzusehen!',
  loginWith: 'Anmelden mit',
  loginWithAccount: 'Melde dich mit deinem Kleinstark-Account an.',
  loginWithApple: 'Anmelden mit Apple',
  loginWithFacebook: 'Anmelden mit Facebook',
  loginWithGoogle: 'Anmelden mit Google',
  loginWithMail: 'Anmelden mit Mail',
  minimumCharacterMessage: 'Mindestens 8 Zeichen',
  newPassword: 'Neues Kennwort',
  noAccountFound: 'Falsches Kennwort oder keinen Account gefunden',
  notInArea: 'Wohl nicht im Liefergebiet',
  onlyBrowse: 'Doch nur stöbern',
  or: 'oder',
  password: 'Kennwort',
  passwordRequestSentMessage:
    'Falls du keine E-Mail erhalten hast, überprüfe deinen Spam-Ordner oder sende die Mail erneut.',
  passwordResetEmailSent:
    'Eine E-Mail mit einem Link zum Zurücksetzen des Kennworts wurde an deine E-Mail-Adresse gesendet.',
  passwordValidation: 'Muss mindestens 8 Zeichen beinhalten',
  phoneNumber: 'Mobilnummer',
  postalCode: 'Postleitzahl',
  postalValidation: 'Leider können wir diese Postleitzahl nicht finden!',
  register: 'Kostenlos Registrieren',
  registerExistDetails:
    'Du hast angegeben, dass du ein neuer Kunde bist, es existiert aber bereits ein Konto mit der E-Mail-Adresse.',
  registerExistHeading: 'E-Mail-Adresse bereits verwendet',
  registerNow: 'Jetzt registrieren',
  registerScreenHeading: 'Fast geschafft',
  registerWithEmail: 'Registrieren mit E-Mail',
  resendEmail: 'E-Mail erneut senden',
  resetPassword: 'Kennwort zurücksetzen',
  savePassword: 'Kennwort speichern',
  signUpCreateAccount: 'Dann erstelle dir einen kostenlosen Account und lege direkt los.',
  signUpNoAccount: 'Du hast noch keinen Account?',
  subscriptionText: 'Ich möchte über Rabatte, Gutscheincodes und Neuigkeiten informiert werden.',
  termsText: 'Ich stimme den |Allgemeinen Geschäftsbedingungen| und der |Datenschutzerklärung| zu.',
  waitingListGoToButton: 'Auf die Warteliste',
  waitingListInputInfo: 'Wir verraten dir als Erstes, wenn wir zu dir liefern.',
  waitingListSuccessDescription: 'Viele regionale Produkte erwarten dich in Aschaffenburg.',
  waitingListSuccessTitle: 'Du bist auf der Warteliste',
  welcomePage1: 'Der Supermarkt & Hofladen für Aschaffenburg',
  welcomePage2: 'Direkt an deine Tür geliefert.',
};
