/* eslint-disable @typescript-eslint/naming-convention */
export const ProfileSettingsTranslationDE = {
  addresses: {
    actions: {
      0: 'Als Lieferadresse festlegen',
      1: 'Als Rechnungsadresse festlegen',
      2: 'Bearbeiten',
      3: 'Löschen',
      4: 'Abbrechen',
    },
    addNewAddress: 'Neue Adresse hinzufügen',
    addresses: 'Adressen',
    billingAddress: 'Rechnungsadresse',
    delete: {
      deleteAddress: 'Adresse löschen',
      keepAddress: 'Adresse behalten',
      question: 'Bist du sicher, dass du diese Adresse löschen willst?',
    },
    editAddress: 'Adresse bearbeiten',
    newAddress: 'Neue Lieferadresse',
    noAddressHeader: 'Keine Adresse gefunden!',
    noAddressText: 'Füge eine Adresse hinzu, damit wir dir das Produktsortiment für deinen Standort anzeigen können.',
    shippingAddress: 'Lieferadresse',
  },
  deleteAccount: {
    confirm: 'Bestätige, indem du | eingibst.',
    deleteAccount: 'Konto löschen',
    infoText1: 'Schade, dass du uns verlassen willst...',
    infoText2:
      'Wenn du dein Konto löschst, kannst du nicht mehr bei uns einkaufen. Falls du noch Rechnungen deiner Bestellungen benötigst, lade diese vor dem Löschen herunter.|Dieser Vorgang kann nicht rückgängig gemacht werden.',
    invalidInput: 'Die Eingabe stimmt nicht!',
    keyword: 'kleinstark-ist-cool',
  },
  help: {
    contact: 'Kontakt',
    emailResponseTime: 'Wir bemühen uns, innerhalb von 24 Stunden auf deine Mail zu antworten.',
    freeOfCharge: 'Gebührenfrei',
    supportHours: 'Montag - Freitag: 09:00 - 17:00 Uhr',
  },
  order: {
    allOrders: 'Alle Bestellungen',
    clock: 'Uhr',
    delivery: 'Zustellung',
    deposit: 'Pfand',
    discoverProducts: 'Produkte entdecken',
    discounts: 'Rabatte',
    downloadInvoice: 'Rechnung herunterladen',
    inclVat: 'inkl. MwSt.',
    noOrdersHeader: 'Noch keine Einkäufe gefunden',
    noOrdersText: 'Suche nach Produkten oder stöbere in den Kategorien.',
    orderDetails: 'Bestelldetails',
    orderedProducts: 'Gekaufte Produkte',
    orderInformation: 'Bestellinformationen',
    orderState: {
      cancelled: 'Storniert',
      confirmed: 'Bestätigt',
      delivered: 'Zugestellt',
      shipped: 'In Zustellung',
    },
    product: {
      1: 'Produkt',
      other: 'Produkte',
    },
    shippingCosts: 'Liefergebühren',
    showAllOrders: 'Alle anzeigen',
    subTotal: 'Zwischensumme',
    total: 'Summe',
    yourOrders: 'Deine Bestellungen',
  },
  overview: {
    addresses: 'Adressen',
    appVersion: 'App Version',
    contact: 'Kontakt',
    expired: 'Abgelaufen',
    faq: 'FAQ',
    feedback: 'Feedback',
    help: 'Hilfe',
    legal: 'Rechtliches',
    legalNotice: 'Impressum',
    logout: 'Ausloggen',
    paymentMethods: 'Zahlungsmethoden',
    personalData: 'Persönliche Daten',
    privacyPolicy: 'Datenschutzerklärung',
    registerNow: 'Jetzt registrieren',
    settings: 'Einstellungen',
    termsAndConditions: 'AGB',
  },
  paymentMethod: {
    delete: 'Löschen',
    keep: 'Behalten',
    noPaymentTypeHeader: 'Keine Zahlungsmethode gefunden!',
    noPaymentTypeText: 'Füge Kreditkarten und Lastschriften an der Kasse hinzu.',
    paymentTypeDeleteHeader: 'Zahlungsart löschen',
    paymentTypeDeleteText: 'Willst du diese Zahlungsart wirklich löschen? Diese Aktion ist nicht umkehrbar.',
  },

  personalData: {
    changePassword: 'Kennwort ändern',
    createdWithApple: 'Du kannst die E-Mail-Adresse nicht ändern, weil der Account mit Apple erstellt wurde.',
    createdWithFacebook: 'Du kannst die E-Mail-Adresse nicht ändern, weil der Account mit Facebook erstellt wurde.',
    createdWithGoogle: 'Du kannst die E-Mail-Adresse nicht ändern, weil der Account mit Google erstellt wurde.',
    currentPassword: 'Aktuelles Passwort',
    deleteAccount: 'Konto löschen...',
    emailNotAvailable: 'Diese Email Adresse wird bereits verwendet',
    emailSent: 'E-Mail wurde erfolgreich gesendet',
    emailUpdateSuccess: 'Deine E-Mail-Adresse wurde erfolgreich gespeichert',
    firstName: 'Vorname',
    forgotPassword: 'Kennwort vergessen',
    lastName: 'Nachname',
    nameError: 'Bitte Namen eingeben',
    newEmailAddress: 'Neue E-Mail-Adresse',
    newsletterChangeSuccess: 'Deine Änderung wurden gespeichert.',
    passwordError: 'Kennwort nicht korrekt!',
    passwordNotMatch: 'Kennwörter stimmen nicht überein!',
    passwordUpdateSuccess: 'Deine Passwort wurde erfolgreich gespeichert',
    personalData: 'Persönliche Daten',
    phoneNumber: 'Mobilnummer',
    repeatPassword: 'Kennwort wiederholen',
    resetPasswordNow: 'Jetzt zurücksetzen',
    saveNewPassword: 'Neues Kennwort speichern',
    saveNewEmailAddress: 'E-Mail-Adresse speichern',
    sendingPasswordResetMail: 'Wir senden dir eine E-Mail zum Zurücksetzen deines Kennworts.',
    updateEmail: 'E-Mail-Adresse ändern',
  },
  settings: 'Einstellungen',
  wallet: {
    balance: 'Guthabenstand',
    balanceInfo:
      'Bei deinem Guthaben unterscheiden wir zwischen auszahlbaren und nicht auszahlbaren Beträgen. Als nicht auszahlbar gilt z.B. Gutscheine. Aktuell kannst du dir :xAmount auszahlen lassen.',
    requestCreditWithdrawal: 'Guthaben Auszahlung beantragen',
    withdrawalInfo:
      'Frage die Auszahlung eines Teils oder deines gesamten Guthabens bei unserem Support an, dieser wird sich dann im Anschluss mit dir in Verbindung setzen.',
    availableAmount: 'verfügbarer Betrag :xAmount',
    requestedAmount: 'gewünschter Betrag',
    requestWithdrawal: 'Auszahlung anfragen',
    toMyWallet: 'Zu meinem Guthabenkonto',
    wallet: 'Guthabenkonto',
    payableAmount: 'davon :xAmount auszahlbar',
    couponCode: 'Gutscheincode',
    redeemCoupon: 'Gutschein einlösen',
    withdrawCash: 'Guthaben auszahlen',
    orderPayment: 'Abbuchung durch Bestellbezahlung',
    supportDebit: 'Abbuchung durch Kleinstark',
    supportCredit: 'Gutschrift durch Kleinstark',
    depositRefund: 'Pfandgutschrift',
    orderGoodwill: 'Gutschrift wegen Reklamation',
    giftCouponCredit: 'Gutschein Einzahlung',
    couponCodeValidation: 'Bitte gib deinen Gutscheincode ein',
    withdrawAmountValidationRequired: 'Gib einen gültigen Wert ein',
    withdrawAmountValidationMax: 'Der gewünschte Betrag überschreitet deinen möglichen Auszahlungsbetrag',
    requestWithdrawSuccess: 'Deine Anfrage wurde gestellt und wir melden uns bei dir',
  },
  complain: {
    additionalInfoOnClaim: 'Zusätzliche Informationen zur Reklamation',
    chooseRedelivery: 'Nachlieferung',
    chooseRedeliveryInfo: 'Je nach Auslastung verfügbar. Wir setzen uns mit dir in Kontakt.',
    chooseRefundInfo:
      'Falls du das Produkt noch heute benötigst, geben wir unser Bestes dir so schnell wir möglich einen Ersatz zu liefern.',
    chooseRefundTitle: 'Wie können wir das wieder gut machen?',
    chooseWallet: 'Gutschrift',
    chooseWalletInfo: 'Unkompliziert auf dein Guthabenkonto',
    complain: 'Reklamation',
    complainContactInfo: 'Ganz einfach in der App eine Gutschrift oder Nachlieferung beantragen.',
    complainInfoTitle: 'Wähle bitte die Produkte aus, die du reklamieren möchtest.',
    complainModalTitle: 'Aus welcher Bestellung möchtest du Produkte reklamieren?',
    complaintReceivedTitle: 'Reklamation erhalten',
    complaintReceivedInfo: 'Wir kontaktieren dich so schnell es geht, um die weitere Abwicklungen zu klären.',
    errorInfo: 'Wähle bitte aus, welche Produkte du reklamieren möchtest.',
    noOrderToComplain: 'Du hast noch keine Bestellung aufgegeben, die du reklamieren kannst.',
    reasonNotArrived: 'Produkt kam nicht an',
    reasonQualityDefect: 'Qualitätsmangel',
    reasonWrongProduct: 'Falsches Produkt geliefert',
    selectReason: 'Reklamationsgrund auswählen',
    send: 'Abschicken',
    submitComplaint: 'Reklamation aufgeben',
  },
};
