require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'


platform :ios, '13.0'

target 'Kleinstark' do
  config = use_native_modules!

  project 'Kleinstark',
  'Debug' => :debug,
  'Release' => :release,
  'DevDebug' => :debug,
  'DevRelease' => :release,
  'ProdDebug' => :debug,
  'ProdRelease' => :release

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )

  # path for react-native-permissions package
  permissions_path = '../node_modules/react-native-permissions/ios'

  # add required pods here
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"


  target 'KleinstarkTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!({ 'Flipper' => '0.138.0', configurations: ['Debug', 'DevDebug', 'ProdDebug'] })
  
  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
