export const ProductDetailTranslationDE = {
  additives: 'Zusatzstoffe',
  alcoholicConfirmationHeader: 'Altersüberprüfung',
  alcoholicConfirmationMessage:
    'Um dieses Produkt kaufen zu können, musst du 18 Jahre oder älter sein. Zur Altersverifikation musst du dich bei der Lieferung deiner Bestellung durch Vorlage deines Personalausweises ausweisen.',
  allergens: 'Allergene',
  alreadyInTheBag: 'In deiner Tasche',
  authModalHeader: 'Ab hier benötigst du einen Account!',
  authModalText:
    'Du verwendest Kleinstark aktuell als Gast. Erstelle einen konstenlosen Account um alle Funktionen nutzen zu können.',
  backSoon: 'Bald zurück',
  backTomorrow: 'Morgen zurück',
  carbohydrate: 'Kohlenhydrate',
  chooseDeliveryDate: 'Ändere deinen Liefertermin, um zu sehen ob das Produkt morgen wieder da ist',
  confirmAge: 'Bin 18 Jahre oder älter',
  cancelAge: 'Bin unter 18 Jahre alt',
  deposit: 'Pfand',
  distanceFromYou: 'km von dir entfernt',
  fat: 'Fett',
  hundredGram: '100 g',
  ingredients: 'Zutaten',
  ingredientsAdditivesAllergens: 'Zutaten, Zusatzstoffe & Allergene',
  inTheBag: 'In die Tasche',
  joinNow: 'Jetzt registrieren',
  kcal: 'Brennwert (kcal)',
  keepBrowsing: 'Weiter stöbern',
  kJ: 'Brennwert (KJ)',
  loginToFavorite: 'Sie müssen eingeloggt sein, um dieses Produkt zu favorisieren',
  notLoggedIn: 'Sie sind nicht eingeloggt',
  nutritionalInformation: 'Nährwertangaben',
  nutritionalValues: 'Nährwerte',
  outOfStockHeader: 'Keine Artikel mehr auf Lager',
  outOfStockText: 'Leider hast du bereits unseren gesamten Vorrat in der Tasche.',
  packagingPreparationStorage: 'Verpackung, Zubereitung & Lagerung',
  per: 'pro',
  preparation: 'Verpackung & Zubereitung',
  protein: 'Eiweiß',
  salt: 'Salz',
  saturatedFat: '- davon gesättigte Fettsäuren',
  storage: 'Lagerung',
  sugar: '- davon Zucker',
  youMightAlsoLike: 'Das könnte dir auch gefallen',
};
